name: JavaDoc

on:
  push:
    branches: [7.0.X, master]
  workflow_dispatch:

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Echo Java Version
        run:  java -version

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      - name: Deploy JavaDoc
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        #uses: JamesIves/github-pages-deploy-action@881db5376404c5c8d621010bcbec0310b58d5e29 #alternate
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: target/reports/apidocs
          target-folder: docs/${{ github.ref_name }}
          branch: gh-pages
